### PR TITLE
feat: Allow workflow to run on PR without creating releases

### PR DESCRIPTION
**Pull request by jubianchi**

### CODE REVIEW

**Review by MarkMcCaskey — COMMENTED** [review]
Looks good, but we should also prevent Slack spam on failure. Currently we'll get a message on slack for every failure in CI in pull requests too

**Review by MarkMcCaskey — APPROVED** [review]
Alright! I think it's probably fine to ship this as is... it just occurred to me though that we also support manually triggering builds... this is useful for reruning if something was broken so we can get the nightly release.  The logic change here means that manually triggered builds on master no longer will be able to actually release.

We can always fix this later though

**Comment by jubianchi** [comment]
@MarkMcCaskey this is actually another good point.

I'll cancel the actual run and push a change to support manually triggering builds from master.

**Comment by jubianchi** [comment]
everything should be good now, merging

**Pull request merged**
